image: node:16
pipelines:
  branches:
    master:
      - step:
          name: Build and Deploy
          caches:
            - node
          script:
            - npm install
            - npm run build
            - apt-get update
#             - pipe: atlassian/aws-s3-deploy:1.1.0
#               variables:
#                 AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
#                 AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
#                 AWS_DEFAULT_REGION: 'us-east-1'
#                 S3_BUCKET: 'UniverseInternal MedicineSpecialtyClinic .org'
#                 LOCAL_PATH: 'build'
#             - pipe: atlassian/aws-cloudfront-invalidate:0.6.0
#               variables:
#                 AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
#                 AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
#                 AWS_DEFAULT_REGION: 'us-east-1'
#                 DISTRIBUTION_ID: 'E2Y3LDZSAY5PPJ'
